/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppFightersRouteRouteImport } from './routes/_app/fighters/route'
import { Route as AppEventsRouteRouteImport } from './routes/_app/events/route'
import { Route as AppFightersIndexRouteImport } from './routes/_app/fighters/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppFightersFighterIdOrSlugRouteImport } from './routes/_app/fighters/$fighterIdOrSlug'
import { Route as AppEventsEventIdOrSlugRouteRouteImport } from './routes/_app/events/$eventIdOrSlug/route'
import { Route as AppEventsEventIdOrSlugIndexRouteImport } from './routes/_app/events/$eventIdOrSlug/index'
import { Route as AppEventsEventIdOrSlugFightIdOrSlugIndexRouteImport } from './routes/_app/events/$eventIdOrSlug/$fightIdOrSlug.index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFightersRouteRoute = AppFightersRouteRouteImport.update({
  id: '/fighters',
  path: '/fighters',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsRouteRoute = AppEventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFightersIndexRoute = AppFightersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFightersRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRouteRoute,
} as any)
const AppFightersFighterIdOrSlugRoute =
  AppFightersFighterIdOrSlugRouteImport.update({
    id: '/$fighterIdOrSlug',
    path: '/$fighterIdOrSlug',
    getParentRoute: () => AppFightersRouteRoute,
  } as any)
const AppEventsEventIdOrSlugRouteRoute =
  AppEventsEventIdOrSlugRouteRouteImport.update({
    id: '/$eventIdOrSlug',
    path: '/$eventIdOrSlug',
    getParentRoute: () => AppEventsRouteRoute,
  } as any)
const AppEventsEventIdOrSlugIndexRoute =
  AppEventsEventIdOrSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppEventsEventIdOrSlugRouteRoute,
  } as any)
const AppEventsEventIdOrSlugFightIdOrSlugIndexRoute =
  AppEventsEventIdOrSlugFightIdOrSlugIndexRouteImport.update({
    id: '/$fightIdOrSlug/',
    path: '/$fightIdOrSlug/',
    getParentRoute: () => AppEventsEventIdOrSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/events': typeof AppEventsRouteRouteWithChildren
  '/fighters': typeof AppFightersRouteRouteWithChildren
  '/$': typeof AppSplatRoute
  '/search': typeof AppSearchRoute
  '/events/$eventIdOrSlug': typeof AppEventsEventIdOrSlugRouteRouteWithChildren
  '/fighters/$fighterIdOrSlug': typeof AppFightersFighterIdOrSlugRoute
  '/events/': typeof AppEventsIndexRoute
  '/fighters/': typeof AppFightersIndexRoute
  '/events/$eventIdOrSlug/': typeof AppEventsEventIdOrSlugIndexRoute
  '/events/$eventIdOrSlug/$fightIdOrSlug/': typeof AppEventsEventIdOrSlugFightIdOrSlugIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof AppSplatRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/fighters/$fighterIdOrSlug': typeof AppFightersFighterIdOrSlugRoute
  '/events': typeof AppEventsIndexRoute
  '/fighters': typeof AppFightersIndexRoute
  '/events/$eventIdOrSlug': typeof AppEventsEventIdOrSlugIndexRoute
  '/events/$eventIdOrSlug/$fightIdOrSlug': typeof AppEventsEventIdOrSlugFightIdOrSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/events': typeof AppEventsRouteRouteWithChildren
  '/_app/fighters': typeof AppFightersRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/events/$eventIdOrSlug': typeof AppEventsEventIdOrSlugRouteRouteWithChildren
  '/_app/fighters/$fighterIdOrSlug': typeof AppFightersFighterIdOrSlugRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/fighters/': typeof AppFightersIndexRoute
  '/_app/events/$eventIdOrSlug/': typeof AppEventsEventIdOrSlugIndexRoute
  '/_app/events/$eventIdOrSlug/$fightIdOrSlug/': typeof AppEventsEventIdOrSlugFightIdOrSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/fighters'
    | '/$'
    | '/search'
    | '/events/$eventIdOrSlug'
    | '/fighters/$fighterIdOrSlug'
    | '/events/'
    | '/fighters/'
    | '/events/$eventIdOrSlug/'
    | '/events/$eventIdOrSlug/$fightIdOrSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/search'
    | '/'
    | '/fighters/$fighterIdOrSlug'
    | '/events'
    | '/fighters'
    | '/events/$eventIdOrSlug'
    | '/events/$eventIdOrSlug/$fightIdOrSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/events'
    | '/_app/fighters'
    | '/_app/$'
    | '/_app/search'
    | '/_app/'
    | '/_app/events/$eventIdOrSlug'
    | '/_app/fighters/$fighterIdOrSlug'
    | '/_app/events/'
    | '/_app/fighters/'
    | '/_app/events/$eventIdOrSlug/'
    | '/_app/events/$eventIdOrSlug/$fightIdOrSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fighters': {
      id: '/_app/fighters'
      path: '/fighters'
      fullPath: '/fighters'
      preLoaderRoute: typeof AppFightersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fighters/': {
      id: '/_app/fighters/'
      path: '/'
      fullPath: '/fighters/'
      preLoaderRoute: typeof AppFightersIndexRouteImport
      parentRoute: typeof AppFightersRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppEventsRouteRoute
    }
    '/_app/fighters/$fighterIdOrSlug': {
      id: '/_app/fighters/$fighterIdOrSlug'
      path: '/$fighterIdOrSlug'
      fullPath: '/fighters/$fighterIdOrSlug'
      preLoaderRoute: typeof AppFightersFighterIdOrSlugRouteImport
      parentRoute: typeof AppFightersRouteRoute
    }
    '/_app/events/$eventIdOrSlug': {
      id: '/_app/events/$eventIdOrSlug'
      path: '/$eventIdOrSlug'
      fullPath: '/events/$eventIdOrSlug'
      preLoaderRoute: typeof AppEventsEventIdOrSlugRouteRouteImport
      parentRoute: typeof AppEventsRouteRoute
    }
    '/_app/events/$eventIdOrSlug/': {
      id: '/_app/events/$eventIdOrSlug/'
      path: '/'
      fullPath: '/events/$eventIdOrSlug/'
      preLoaderRoute: typeof AppEventsEventIdOrSlugIndexRouteImport
      parentRoute: typeof AppEventsEventIdOrSlugRouteRoute
    }
    '/_app/events/$eventIdOrSlug/$fightIdOrSlug/': {
      id: '/_app/events/$eventIdOrSlug/$fightIdOrSlug/'
      path: '/$fightIdOrSlug'
      fullPath: '/events/$eventIdOrSlug/$fightIdOrSlug/'
      preLoaderRoute: typeof AppEventsEventIdOrSlugFightIdOrSlugIndexRouteImport
      parentRoute: typeof AppEventsEventIdOrSlugRouteRoute
    }
  }
}

interface AppEventsEventIdOrSlugRouteRouteChildren {
  AppEventsEventIdOrSlugIndexRoute: typeof AppEventsEventIdOrSlugIndexRoute
  AppEventsEventIdOrSlugFightIdOrSlugIndexRoute: typeof AppEventsEventIdOrSlugFightIdOrSlugIndexRoute
}

const AppEventsEventIdOrSlugRouteRouteChildren: AppEventsEventIdOrSlugRouteRouteChildren =
  {
    AppEventsEventIdOrSlugIndexRoute: AppEventsEventIdOrSlugIndexRoute,
    AppEventsEventIdOrSlugFightIdOrSlugIndexRoute:
      AppEventsEventIdOrSlugFightIdOrSlugIndexRoute,
  }

const AppEventsEventIdOrSlugRouteRouteWithChildren =
  AppEventsEventIdOrSlugRouteRoute._addFileChildren(
    AppEventsEventIdOrSlugRouteRouteChildren,
  )

interface AppEventsRouteRouteChildren {
  AppEventsEventIdOrSlugRouteRoute: typeof AppEventsEventIdOrSlugRouteRouteWithChildren
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppEventsRouteRouteChildren: AppEventsRouteRouteChildren = {
  AppEventsEventIdOrSlugRouteRoute:
    AppEventsEventIdOrSlugRouteRouteWithChildren,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppEventsRouteRouteWithChildren = AppEventsRouteRoute._addFileChildren(
  AppEventsRouteRouteChildren,
)

interface AppFightersRouteRouteChildren {
  AppFightersFighterIdOrSlugRoute: typeof AppFightersFighterIdOrSlugRoute
  AppFightersIndexRoute: typeof AppFightersIndexRoute
}

const AppFightersRouteRouteChildren: AppFightersRouteRouteChildren = {
  AppFightersFighterIdOrSlugRoute: AppFightersFighterIdOrSlugRoute,
  AppFightersIndexRoute: AppFightersIndexRoute,
}

const AppFightersRouteRouteWithChildren =
  AppFightersRouteRoute._addFileChildren(AppFightersRouteRouteChildren)

interface AppRouteRouteChildren {
  AppEventsRouteRoute: typeof AppEventsRouteRouteWithChildren
  AppFightersRouteRoute: typeof AppFightersRouteRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEventsRouteRoute: AppEventsRouteRouteWithChildren,
  AppFightersRouteRoute: AppFightersRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
