/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AuthStartRouteImport } from './routes/_auth/start'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthJoinRouteImport } from './routes/_auth/join'
import { Route as AppWaitlistRouteImport } from './routes/_app/waitlist'
import { Route as DemoGameIdIndexRouteImport } from './routes/demo/$gameId/index'
import { Route as DemoGameIdLobbyRouteImport } from './routes/demo/$gameId/lobby'
import { Route as DemoGameIdDraftRouteImport } from './routes/demo/$gameId/draft'

const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJoinRoute = AuthJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWaitlistRoute = AppWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoGameIdIndexRoute = DemoGameIdIndexRouteImport.update({
  id: '/$gameId/',
  path: '/$gameId/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoGameIdLobbyRoute = DemoGameIdLobbyRouteImport.update({
  id: '/$gameId/lobby',
  path: '/$gameId/lobby',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoGameIdDraftRoute = DemoGameIdDraftRouteImport.update({
  id: '/$gameId/draft',
  path: '/$gameId/draft',
  getParentRoute: () => DemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/demo': typeof DemoRouteRouteWithChildren
  '/waitlist': typeof AppWaitlistRoute
  '/join': typeof AuthJoinRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/start': typeof AuthStartRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/$gameId/draft': typeof DemoGameIdDraftRoute
  '/demo/$gameId/lobby': typeof DemoGameIdLobbyRoute
  '/demo/$gameId': typeof DemoGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/waitlist': typeof AppWaitlistRoute
  '/join': typeof AuthJoinRoute
  '/login': typeof AuthLoginRoute
  '/sign-up': typeof AuthSignUpRoute
  '/start': typeof AuthStartRoute
  '/demo': typeof DemoIndexRoute
  '/demo/$gameId/draft': typeof DemoGameIdDraftRoute
  '/demo/$gameId/lobby': typeof DemoGameIdLobbyRoute
  '/demo/$gameId': typeof DemoGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/_app/waitlist': typeof AppWaitlistRoute
  '/_auth/join': typeof AuthJoinRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/start': typeof AuthStartRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/$gameId/draft': typeof DemoGameIdDraftRoute
  '/demo/$gameId/lobby': typeof DemoGameIdLobbyRoute
  '/demo/$gameId/': typeof DemoGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demo'
    | '/waitlist'
    | '/join'
    | '/login'
    | '/sign-up'
    | '/start'
    | '/demo/'
    | '/demo/$gameId/draft'
    | '/demo/$gameId/lobby'
    | '/demo/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/waitlist'
    | '/join'
    | '/login'
    | '/sign-up'
    | '/start'
    | '/demo'
    | '/demo/$gameId/draft'
    | '/demo/$gameId/lobby'
    | '/demo/$gameId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/demo'
    | '/_app/waitlist'
    | '/_auth/join'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_auth/start'
    | '/demo/'
    | '/demo/$gameId/draft'
    | '/demo/$gameId/lobby'
    | '/demo/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/_auth/start': {
      id: '/_auth/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/join': {
      id: '/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthJoinRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/waitlist': {
      id: '/_app/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AppWaitlistRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/demo/$gameId/': {
      id: '/demo/$gameId/'
      path: '/$gameId'
      fullPath: '/demo/$gameId'
      preLoaderRoute: typeof DemoGameIdIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/$gameId/lobby': {
      id: '/demo/$gameId/lobby'
      path: '/$gameId/lobby'
      fullPath: '/demo/$gameId/lobby'
      preLoaderRoute: typeof DemoGameIdLobbyRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/$gameId/draft': {
      id: '/demo/$gameId/draft'
      path: '/$gameId/draft'
      fullPath: '/demo/$gameId/draft'
      preLoaderRoute: typeof DemoGameIdDraftRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppWaitlistRoute: typeof AppWaitlistRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWaitlistRoute: AppWaitlistRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthJoinRoute: typeof AuthJoinRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthStartRoute: typeof AuthStartRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthJoinRoute: AuthJoinRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthStartRoute: AuthStartRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoIndexRoute: typeof DemoIndexRoute
  DemoGameIdDraftRoute: typeof DemoGameIdDraftRoute
  DemoGameIdLobbyRoute: typeof DemoGameIdLobbyRoute
  DemoGameIdIndexRoute: typeof DemoGameIdIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoIndexRoute: DemoIndexRoute,
  DemoGameIdDraftRoute: DemoGameIdDraftRoute,
  DemoGameIdLobbyRoute: DemoGameIdLobbyRoute,
  DemoGameIdIndexRoute: DemoGameIdIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
